ALTER TABLE `User`
  ADD COLUMN `companyName` VARCHAR(191) NULL,
  ADD COLUMN `siret` VARCHAR(191) NULL,
  ADD COLUMN `address` VARCHAR(191) NULL,
  ADD COLUMN `phone` VARCHAR(191) NULL,
  ADD COLUMN `mobile` VARCHAR(191) NULL,
  ADD COLUMN `billingAddress` VARCHAR(191) NULL,
  ADD COLUMN `shippingAddress` VARCHAR(191) NULL,
  ADD COLUMN `billingEmail` VARCHAR(191) NULL,
  ADD COLUMN `vatNumber` VARCHAR(191) NULL;
